name: $(Build.SourceBranchName)-$(Build.SourceVersion)

resources:
  - repo: self

variables:
  esy__ci_cache_version: v1    # this is available to all jobs in env as $ESY__CI_CACHE_VERSION or in azure config as $(esy__ci_cache_version)

trigger:
  - master
  - bryphe/*
  - andreypopp/*
  - zindel/*
  - prometheansacrifice/*

jobs:
  - template: build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-latest

  - template: build-platform.yml
    parameters:
      platform: Ubuntu_16_04
      vmImage: ubuntu-16.04

  - template: build-platform.yml
    parameters:
      platform: macOS_10_12
      vmImage: macOS-latest

  - template: build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-latest

  - template: build-cross.yml
    parameters:
      platform: linux_musl_arm64
      target: linux.musl.arm64
      vmImage: ubuntu-latest

  - template: build-cross.yml
    parameters:
      platform: linux_musl_x86_64
      target: linux.musl.x86_64
      vmImage: ubuntu-latest

  - job: Alpine_Build
    displayName: Alpine Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        submodules: true
      - template: utils/use-node.yml
      - script: sudo apt install jq gzip
        displayName: Install deps
      - bash: |
          ESY__PROJECT_NAME=$(jq -r .name package.json)
          ESY__PROJECT_VERSION=$(jq -r .version package.json)
          echo "##vso[task.setvariable variable=esy__project_name]$ESY__PROJECT_NAME"
          echo "##vso[task.setvariable variable=esy__project_version]$ESY__PROJECT_VERSION"
      - script: docker build . --network=host -t esy:nightly-alpine-latest
        displayName: "Docker Build (Alpine)"
      - script: docker container run -itd --network=host --name esy-container esy:nightly-alpine-latest
        displayName: "Run Docker Container"
      - script:  docker cp esy-container:/app/_release $PWD/_container_release
        displayName: "Copy _release from container"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Docker built artifact"
        inputs:
          PathtoPublish: "_container_release"
          ArtifactName: AlpineLinux
      - script: docker save $(esy__project_name) | gzip > $(esy__project_name)-docker-image.tar.gz
        displayName: "Save Docker image as tarball"
      - task: PublishBuildArtifacts@1
        displayName: "Publish Docker production image"
        inputs:
          PathtoPublish: "$(esy__project_name)-docker-image.tar.gz"
          ArtifactName: AlpineLinuxDockerBuiltNPM
          
  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - template: build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-latest
      demands: node.js
    steps:
      - template: cross-release.yml
        
  # # This job is kept here as we want to have the platform names in the same file
  # - job: Release
  #   displayName: Release
  #   dependsOn:
  #     - Linux
  #     - macOS
  #     - Windows
  #   pool:
  #     vmImage: ubuntu-latest
  #   steps:
    # - script: |
    #     node scripts/make-release-skeleton.js
    #   displayName: 'Prepare release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download Linux Artifacts'
    #   inputs:
    #     artifactName: Linux
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download macOS Artifacts'
    #   inputs:
    #     artifactName: macOS_10_12
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download macOS Artifacts'
    #   inputs:
    #     artifactName: macOS
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download Windows Artifacts'
    #   inputs:
    #     artifactName: Windows
    #     downloadPath: '_release'

    # - task: PublishBuildArtifacts@1
    #   displayName: 'Publish Artifact: Release'
    #   inputs:
    #     PathtoPublish: '_release'
    #     ArtifactName: release
