name: $(Build.SourceBranchName)-$(Build.SourceVersion)

resources:
  - repo: self

variables:
  esy__ci_cache_version: v1    # this is available to all jobs in env as $ESY__CI_CACHE_VERSION or in azure config as $(esy__ci_cache_version)
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    dockerJobCommand: "buildAndPush"
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    dockerJobcommand: "build"

trigger:
  - master

pr:
  - master

jobs:
  - template: build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-latest

  # Platforms we no longer run on:
  #  - ubuntu-16.04
  #  - macos 10.12

  - template: build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-latest

  - template: docker.yml
    parameters:
      platform: Docker
      vmImage: ubuntu-latest
      jobCommand: dockerJobcommand

  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - template: build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Alpine_Build
      - macOS
      - Windows
    pool:
      vmImage: macOS-latest
      demands: node.js
    steps:
      - template: cross-release.yml
