name: $(Build.SourceBranchName)-$(Build.SourceVersion)

resources:
  - repo: self

trigger:
  - 0.3.x
  - master
  - bryphe/*
  - andreypopp/*

jobs:
  - job: buildLinux
    displayName: Build Linux
    condition: succeeded()
    pool:
        vmImage: ubuntu-16.04

    steps:
      - script: sudo apt-get update
      - script: sudo apt-get install -y libcurl4-gnutls-dev libssl-dev libgmp-dev
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Platform Release'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-linux

  - job: buildMacos
    displayName: Build macOS
    condition: succeeded()
    pool:
      vmImage: macOS-10.13
      demands: node.js

    steps:
      - script: brew install gmp
      - template: build-nix.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Platform Release'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-darwin

  - job: buildWindows
    displayName: Windows
    condition: succeeded()
    timeoutInMinutes: 0
    pool:
      vmImage: vs2017-win2016
      demands: npm

    steps:
      - template: build-windows.yml

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Windows'
        inputs:
          PathtoPublish: '_platformrelease'
          ArtifactName: platform-win32

  - job: buildRelease
    displayName: Build Release
    dependsOn:
      - buildLinux
      - buildMacos
      - buildWindows
    condition: succeeded()
    pool:
      vmImage: ubuntu-16.04

    steps:

    - script: |
        node scripts/make-release-skeleton.js
      displayName: 'Prepare release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Linux Artifacts'
      inputs:
        artifactName: platform-linux
        downloadPath: '_release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download macOS Artifacts'
      inputs:
        artifactName: platform-darwin
        downloadPath: '_release'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Windows Artifacts'
      inputs:
        artifactName: platform-win32
        downloadPath: '_release'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Release'
      inputs:
        PathtoPublish: '_release'
        ArtifactName: release
