name: $(Build.SourceBranchName)-$(Build.SourceVersion)

resources:
  - repo: self

variables:
  esy__ci_cache_version: v1    # this is available to all jobs in env as $ESY__CI_CACHE_VERSION or in azure config as $(esy__ci_cache_version)

trigger:
  - master
  - bryphe/*
  - andreypopp/*
  - zindel/*
  - prometheansacrifice/*

jobs:
  - template: build-platform.yml
    parameters:
      platform: Linux
      vmImage: ubuntu-latest

  - template: build-platform.yml
    parameters:
      platform: macOS_10_12
      vmImage: macOS-latest

  - template: build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-latest

  - job: Alpine_Build
    displayName: Alpine Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: docker build . --network=host -t esy:nightly-alpine-latest

  # Need windows-2019 to do esy import/export-dependencies
  # which assumes you have bsdtar (tar.exe) in your system
  # otherwise it will end up using the esy-bash tar which doesn't
  # understand drives like D:/ (thinks it's an scp path).
  - template: build-platform.yml
    parameters:
      platform: Windows
      vmImage: windows-2019

  # This job is kept here as we want to have the platform names in the same file
  - job: Release
    displayName: Release
    dependsOn:
      - Linux
      - macOS
      - Windows
    pool:
      vmImage: macOS-latest
      demands: node.js
    steps:
      - template: cross-release.yml
        
  # # This job is kept here as we want to have the platform names in the same file
  # - job: Release
  #   displayName: Release
  #   dependsOn:
  #     - Linux
  #     - macOS
  #     - Windows
  #   pool:
  #     vmImage: ubuntu-latest
  #   steps:
    # - script: |
    #     node scripts/make-release-skeleton.js
    #   displayName: 'Prepare release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download Linux Artifacts'
    #   inputs:
    #     artifactName: Linux
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download macOS Artifacts'
    #   inputs:
    #     artifactName: macOS_10_12
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download macOS Artifacts'
    #   inputs:
    #     artifactName: macOS
    #     downloadPath: '_release'

    # - task: DownloadBuildArtifacts@0
    #   displayName: 'Download Windows Artifacts'
    #   inputs:
    #     artifactName: Windows
    #     downloadPath: '_release'

    # - task: PublishBuildArtifacts@1
    #   displayName: 'Publish Artifact: Release'
    #   inputs:
    #     PathtoPublish: '_release'
    #     ArtifactName: release
