---
# default parameters
parameters:
  platform: "Docker (on latest Ubuntu)"
  vmImage: ubuntu-latest
  jobCommand: "build"

jobs:
  - job: Alpine_Build
    displayName: Alpine Build
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: self
        submodules: true
      - template: utils/use-node.yml
      - script: sudo apt install jq gzip
        displayName: Install deps
      - bash: |
          ESY__PROJECT_NAME=$(jq -r .name package.json)
          ESY__PROJECT_VERSION=$(jq -r .version package.json)
          echo "##vso[task.setvariable variable=esy__project_name]$ESY__PROJECT_NAME"
          echo "##vso[task.setvariable variable=esy__project_version]$ESY__PROJECT_VERSION"

      - task: Docker@2
        displayName: 'Push esydev/esy:nightly-alpine-latest to Docker Hub'
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        inputs:
          containerRegistry: 'Docker Esy (nightly)'
          repository: 'esydev/esy'
          command: ${{parameters.jobCommand}}
          buildContext: '.'
          Dockerfile: 'dockerfiles/alpine.Dockerfile'
          tags: |
            nightly-alpine-latest
            nightly-alpine

      - script: docker container run --pull=never -itd --network=host --name esy-container esydev/esy:nightly-alpine-latest
        displayName: "Run Docker Container"

      - script: docker cp esy-container:/app/_release $PWD/_container_release
        displayName: "Copy _release from container"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Docker built artifact"
        inputs:
          PathtoPublish: "_container_release"
          ArtifactName: AlpineLinux

      - script: docker save $(esy__project_name) | gzip > $(esy__project_name)-docker-image.tar.gz
        displayName: "Save Docker image as tarball"

      - task: PublishBuildArtifacts@1
        displayName: "Upload Docker production image (as Azure artifacts)"
        inputs:
          PathtoPublish: "$(esy__project_name)-docker-image.tar.gz"
          ArtifactName: AlpineLinuxDockerBuiltNPM

