---
name: Test deployment

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'site/**'
    branches:
      - master

jobs:
  test-deploy:
    name: Test documentation deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: site
      - name: Test build website
        run: yarn build
        working-directory: site
